testing:
  enable: true
  defaultSql: "SELECT * FROM t_user;\nSELECT * FROM t_user tu \nwhere tu.enabled = 1\norder by tu.username\n;"

query:
  maxRows: 10000

showResult:
  maxRows: 20
  maxColumns: 7

database-validation:
  oracle: select 1 from dual
  mysql: select 1
  sqlserver: select 1